# Generated by Django 2.2 on 2023-08-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Essential', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
